environment:
  global:
    RUST_VERSION: stable
    TARGET: x86_64-pc-windows-msvc

install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain %RUST_VERSION%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustup component add rustfmt
  - rustc -Vv
  - cargo -V

test_script:
  - cargo fmt --all -- --check
  - cargo test --target %TARGET%

build: false
